### ISSUE TITLE
Django Library Files mistakenly uploaded in place of project folder.

### ISSUE THREAD

**Issue by aswinshenoy** [akhilam512/FormWebApp-Django-#2]
Hey Akhil,

You have mistakenly commited the Django Library Folder (installed in your PC, which essentially is like the program files) instead of the Django Project folder. Please upload the project folder replacing this. 

The Django project folder is the one from which you execute manage.py to runserver or to perfom migrations. Also remember it is not recommended to upload the db.sqlite3 database file.

Cheers!

**Comment by akhilam512** [comment]
Thanks for that @aswinshenoy
